//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax_Practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int Id { get; set; }
        public int MarkaId { get; set; }
        public string Name { get; set; }
    
        public virtual Marka Marka { get; set; }
    }
}
